export const FETCH_DIALOGS_REQUEST = 'FETCH_DIALOGS_REQUEST';
export const FETCH_DIALOGS_SUCCESS = 'FETCH_DIALOGS_SUCCESS';
export const FETCH_DIALOGS_FAILURE = 'FETCH_DIALOGS_FAILURE';

export const FETCH_DIALOG_STATUS_REQUEST = 'FETCH_DIALOG_STATUS_REQUEST';
export const FETCH_DIALOG_STATUS_SUCCESS = 'FETCH_DIALOG_STATUS_SUCCESS';
export const FETCH_DIALOG_STATUS_FAILURE = 'FETCH_DIALOG_STATUS_FAILURE';
