export const FETCH_THEMES_REQUEST = 'FETCH_THEMES_REQUEST';
export const FETCH_THEMES_SUCCESS = 'FETCH_THEMES_SUCCESS';
export const FETCH_THEMES_FAILURE = 'FETCH_THEMES_FAILURE';

export const ENTER_CHAT_REQUEST = 'ENTER_CHAT_REQUEST';
export const ENTER_CHAT_SUCCESS = 'ENTER_CHAT_SUCCESS';
export const ENTER_CHAT_FAILURE = 'ENTER_CHAT_FAILURE';

export const ENTER_CHAT_RESET = 'ENTER_CHAT_RESET';
