export const GET_DEVICE_STATE_REQUEST = 'GET_DEVICE_STATE_REQUEST';
export const GET_DEVICE_STATE_SUCCESS = 'GET_DEVICE_STATE_SUCCESS';
export const GET_DEVICE_STATE_FAILURE = 'GET_DEVICE_STATE_FAILURE';
