export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const FETCH_CURRENT_DIALOG_REQUEST = 'FETCH_CURRENT_DIALOG_REQUEST';
export const FETCH_CURRENT_DIALOG_SUCCESS = 'FETCH_CURRENT_DIALOG_SUCCESS';
export const FETCH_CURRENT_DIALOG_FAILURE = 'FETCH_CURRENT_DIALOG_FAILURE';
