export const UPLOAD_TO_STORAGE_REQUEST = 'UPLOAD_TO_STORAGE_REQUEST';
export const UPLOAD_TO_STORAGE_SUCCESS = 'UPLOAD_TO_STORAGE_SUCCESS';
export const UPLOAD_TO_STORAGE_FAILURE = 'UPLOAD_TO_STORAGE_FAILURE';
